# -*- mode: ruby -*-
# vi: set ft=ruby :
#export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|
  number_of_machines = 1
  box_name = "generic/ubuntu2004"
  
  base_ip = 100
  base_ip_addresses = "192.168.55"
  
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  
  script = <<-SCRIPT
    echo "hello world"
    apt update
  SCRIPT
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "node0#{i}" do |box|
      box.vm.box = box_name
      
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"
  
      box.vm.hostname = "node0#{i}"
      box.vm.provision "shell", inline: "#{script}"

    end
  end
end
