---
- name: Update apt
  apt: update_cache=yes

- name: Add the APT Key for ClickHouse.
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: E0C56BD4
    state: present
  become: true

- name: add clickhouse repo
  ansible.builtin.apt_repository:
    repo: deb https://repo.clickhouse.com/deb/stable/ main/
    state: present
    filename: clickhouse.list

- name: Install Clickhouse Packages
  apt: name={{ item }} state=latest
  loop:
    - 'clickhouse-server'
    - 'clickhouse-client'

- name: Restart service clickhouse service 
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: clickhouse-server

- name: Create ClickHouse databases
  command: clickhouse-client --query="CREATE DATABASE {{ item }};"
  loop: "{{ clickhouse_databases | default([]) }}"
  register: command_result
  changed_when: command_result.rc == 0
  failed_when: command_result.rc != 0 and command_result.rc != 82

- name: Create ClickHouse destination table
  changed_when: no
  command: >
    clickhouse-client --query
    "CREATE TABLE IF NOT EXISTS db.local_data (
       id Int64,
       title String,
       description String,
       content String,
       date Date
    )
    ENGINE = MergeTree()
    PARTITION BY toYYYYMM(date)
    ORDER BY id;"

- name: insert data into local_data
  changed_when: no
  command: >
    clickhouse-client --query
    "{{ item }}"
  loop:
    - "INSERT INTO db.local_data (*) VALUES (1, 'title1', 'description1', 'content1', '2020-10-10')"
    - "INSERT INTO db.local_data (*) VALUES (2, 'title2', 'description2', 'content2', '2020-10-10')"
    - "INSERT INTO db.local_data (*) VALUES (3, 'title3', 'description3', 'content3', '2020-10-10')"
    - "INSERT INTO db.local_data (*) VALUES (4, 'title4', 'description4', 'content4', '2020-10-10')"
    - "INSERT INTO db.local_data (*) VALUES (5, 'title5', 'description5', 'content5', '2020-10-10')"
    - "INSERT INTO db.local_data (*) VALUES (6, 'title6', 'description6', 'content6', '2020-10-10')"
    - "INSERT INTO db.local_data (*) VALUES (7, 'title7', 'description7', 'content7', '2020-10-10')"
    - "INSERT INTO db.local_data (*) VALUES (8, 'title8', 'description8', 'content8', '2020-10-10')"
    - "INSERT INTO db.local_data (*) VALUES (9, 'title9', 'description9', 'content9', '2020-10-10')"
    - "INSERT INTO db.local_data (*) VALUES (10,'title10','description10','content10','2020-10-10')"

- name: Creates directory
  file:
    path: /opt/ch/backups
    state: directory
    owner: clickhouse
    group: clickhouse

- name: freeze partitions for db.local_data
  changed_when: no
  command: >
    clickhouse-client --query
    "{{ item }}"
  loop:
    - "ALTER TABLE db.local_data FREEZE PARTITION '202010';"

- name: copy from freezed partitions to backup folder
  changed_when: no
  command: >
    cp -r /var/lib/clickhouse/shadow/. /opt/ch/backups

- name: copy db.local_data table metadata
  changed_when: no
  command: >
    cp /var/lib/clickhouse/metadata/db/local_data.sql /opt/ch/backups

- name: restore table in db_restore database 
  changed_when: no
  shell: >
     sed '1 s/.*/CREATE TABLE local_data/' /opt/ch/backups/local_data.sql | clickhouse-client --database db_restore

- name: copy from freezed partitions to new databases db_restore.local_data
  changed_when: no
  command: >
    cp -r /opt/ch/backups/. /var/lib/clickhouse/data/db_restore/local_data/detached/

- name: change owner of the files for restored backups
  changed_when: no
  command: >
    chown -R clickhouse:clickhouse /var/lib/clickhouse/data/db_restore/local_data/detached

#https://highload.today/bekap-i-vosstanovlenie-v-clickhouse/
