# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder"./","/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt install default-jre-headless -y
    java --version
    
    mkdir -p /opt/zookeeper
    cd /opt/zookeeper
    wget https://apache.volia.net/zookeeper/zookeeper-3.6.3/apache-zookeeper-3.6.3-bin.tar.gz
    tar xzfv apache-zookeeper-3.6.3-bin.tar.gz
    mv apache-zookeeper-3.6.3-bin/* ./
    rm -rf apache-zookeeper-3.6.3-bin apache-zookeeper-3.6.3-bin.tar.gz
    ls
    cat << EOF > conf/zoo.cfg
tickTime=2000
dataDir=/var/lib/zookeeper
clientPort=2181
EOF

    ./bin/zkServer.sh start
    
#    ./bin/zkCli.sh -server localhost:2181
    
    ./bin/zkServer.sh stop
    useradd -M zookeeper
    chown -R zookeeper:zookeeper /opt/zookeeper/
    chown -R zookeeper:zookeeper /var/lib/zookeeper/
    cat << EOF > /lib/systemd/system/zookeeper.service
Description=zookeeper:3.6.3
After=network.target

[Service]
Type=forking
User=zookeeper
Group=zookeeper

WorkingDirectory=/opt/zookeeper

ExecStart=/opt/zookeeper/bin/zkServer.sh start
ExecStop=/opt/zookeeper/bin/zkServer.sh stop
ExecReload=/opt/zookeeper/bin/zkServer.sh restart

RestartSec=30
Restart=always

PrivateTmp=yes
PrivateDevices=yes

LimitCORE=infinity
LimitNOFILE=500000

[Install]
WantedBy=multi-user.target
Alias=zookeeper.service
EOF
    service zookeeper start
    service zookeeper status

  SHELL
end
