---
- hosts: server1
  become: yes
  vars:
    wireguard_port: "5888"
    wireguard_path: "/etc/wireguard"
    wireguard_sources_path: "/var/cache"
    wireguard_network_name: "private"
    debian_enable_backports: true
    debian_pin_packages: true
    client_vpn_ip: "10.1.0.100/8"
    client_wireguard_path: "~/wg.conf"
    client_wireguard_dns: false
    wireguard_additional_peers: false
    wireguard_post_up: false
    wireguard_post_down: false
  tasks:
  - name: ensure packages is installed 
    apt:
      pkg:
      - vim
      - apt-transport-https
      - wget
      - gnupg2
      - wireguard
      - curl
      - unzip
      - qrencode
      - gnutls-bin
      - software-properties-common
      update_cache: yes
      state: latest

#  - name: print all facts
#    ansible.builtin.debug:
#      var: ansible_facts
   
  - name: Installing tinc package
    apt:
      pkg: tinc
      update_cache: yes
      state: latest

  - name: Ensure wireguard_path exists as directory
    file:
      path: "{{ wireguard_path }}"
      state: directory
  
  - name: Read private key
    stat:
      path: "{{ wireguard_path }}/privatekey"
    register: privatekey
    when: not ansible_check_mode
  
  - name: Generate wireguard keys
    shell: set -o pipefail && \
           umask 077; wg genkey | tee {{ wireguard_path  }}/privatekey | wg pubkey > {{ wireguard_path }}/publickey
    args:
      executable: /bin/bash
    when:
      - not ansible_check_mode
      - not privatekey.stat.exists

  - name: Read public key
    slurp:
      src: "{{ wireguard_path }}/publickey"
    register: public
    when: not ansible_check_mode
  
  - name: Read private client's key
    stat:
      path: "{{ wireguard_path }}/client_privatekey"
    register: client_privatekey
    run_once: true
    when: client_vpn_ip | length > 0
  
  - name: Generate wireguard client's keys
    shell: set -o pipefail && \
           umask 077; wg genkey | tee {{ wireguard_path  }}/client_privatekey | wg pubkey > {{ wireguard_path }}/client_publickey
    run_once: true
    args:
      executable: /bin/bash
    when:
      - client_vpn_ip | length > 0
      - not client_privatekey.stat.exists
  
  - name: Read private client's key
    slurp:
      src: "{{ wireguard_path }}/client_privatekey"
    register: client_privatekey
    run_once: true
    when:
      - not ansible_check_mode
      - client_vpn_ip | length > 0
  
  - name: Read public client's key
    slurp:
      src: "{{ wireguard_path }}/client_publickey"
    register: client_publickey
    run_once: true
    when:
      - not ansible_check_mode
      - client_vpn_ip | length > 0
  
  - name: Generate configs
    template:
      src: templates/interface.conf.j2
      dest: "{{ wireguard_path }}/{{ wireguard_network_name }}.conf"
      owner: root
      group: root
      mode: "u=rw,g=r,o="
    register: config
    notify:
      - Enable wg-quick service
      - Restart wg-quick service
    when: not ansible_check_mode
  


  handlers:
  - name: restart pritunl
    ansible.builtin.service:
      name: pritunl
      daemon_reload: yes
      state: restarted

  - name: restart tinc
    ansible.builtin.service:
      name: tinc
      daemon_reload: yes
      state: restarted

  - name: Enable wg-quick service
    service:
      name: "wg-quick@{{ wireguard_network_name }}"
      enabled: yes
  
  - name: Restart wg-quick service
    service:
      name: "wg-quick@{{ wireguard_network_name }}"
      state: restarted
    when: config.changed
  
