# -*- mode: ruby -*-
# vi: set ft=ruby :
#export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|
  number_of_machines = 1
  box_name = "lxc_1"
  
  base_ip = 100
  base_ip_addresses = "192.168.51"
  
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  
  script = <<-SCRIPT
    echo "hello world"
  SCRIPT
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.box = 'generic/ubuntu1804'
  config.vm.network "private_network", ip: "192.168.52.100"
  config.vm.define 'lxcVM'
  config.vm.disk :disk, name: "lxc_1", size: "2GB"
  config.vm.disk :disk, name: "lxc_2", size: "2GB"
  config.vm.disk :disk, name: "lxc_3", size: "2GB"


#  (1..number_of_machines).each do |i|
#    config.vm.define "box_#{i}" do |box|
#      box.vm.box = box_name
#      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"
#      box.vm.disk :disk, name: "backup_#{i}", size: "2GB"
#  
#      box.vm.provision "shell", inline: "#{script}"
#    end
#  end
end
