---
- name: Install Nginx
  apt: name=nginx state=latest

- name: Install php7.4-fpm
  apt: name=php7.4-fpm state=latest

- name: Change default nginx site
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: Install PHP Packages
  apt: name={{ php_packages }} state=latest
