Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.network :private_network, ip: "192.168.33.101"
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        #ansible.verbose='vvv'#accepted values:from'v'to'vvvv'
    end
end
