version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090
  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager.yml:/config/alertmanager.yml"
    command: --config.file=/config/alertmanager.yml --log.level=debug
  grafana:
    image: grafana/grafana:5.0.0   
#    ports:
#      - 3000:3000
    expose:
      - 3000
    network_mode: host
