# -*- mode: ruby -*-
# vi: set ft=ruby :
#export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|
  number_of_machines = 1
  box_name = "generic/ubuntu2004"
  
  base_ip = 100
  base_ip_addresses = "192.168.56"
  
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  
  script = <<-SCRIPT
    echo "hello world"
  SCRIPT
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "dhcp#{i}" do |box|
      box.vm.box = box_name
      
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"
      box.vm.network "private_network", ip: "10.10.10.1", auto_config: false
  
      box.vm.hostname = "dhcp#{i}"
#      box.vm.provision "shell", inline: "#{script}"

#      config.vm.provision "ansible" do |ansible|
      box.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbook.yml"
          #ansible.verbose='vvv'#accepted values:from'v'to'vvvv'
      end


      #if "iscsi#{i}"  == "iscsi1" then
			#  box.vm.disk :disk, name: "lxc_1", size: "2GB"
      #end
    end
  end
end
