$script = <<-SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
sudo apt update
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "cpu1" do |lab1b|
    lab1b.vm.box = "generic/ubuntu2004"
    lab1b.vm.hostname = "cpu1"
    lab1b.vm.network "private_network", ip: "192.168.56.100"
    lab1b.vm.provision "shell", inline: $script
    lab1b.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
  end
end
