# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  number_of_machines = 2
  box_name = "generic/ubuntu1804"
  
  base_ip = 100
  base_ip_addresses = "192.168.51"
  
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  
  script = <<-SCRIPT
    echo "hello world"
  SCRIPT
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "box_#{i}" do |box|
      box.vm.box = box_name
      box.vm.box = box_name
      if "box_#{i}"  == "box_1" then                                                                                                                                               
        box.vm.box = "generic/ubuntu2004"
      end
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"
      box.vm.disk :disk, name: "backup_#{i}", size: "2GB"
  
      box.vm.provision "shell", inline: "#{script}"
			box.vm.hostname = "server#{i}"
      box.vm.network "forwarded_port", guest: 80, host: "808#{i}"
    end
  end
end
