Vagrant.configure("2") do |config|
  config.vm.define "cpu1" do |vm1|
    vm1.vm.box = "generic/ubuntu2004"
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.56.100", virtualbox__intnet: true
    vm1.vm.provision "shell", path: "./script.sh"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end
  config.vm.define "cpu2" do |vm2|
    vm2.vm.box = "generic/ubuntu2004"
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.56.200", virtualbox__intnet: true
    vm2.vm.provision "shell", path: "./script.sh"
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
#
#
#Vagrant.configure("2") do |config|
#  config.vm.provision "shell", inline: "echo Hello"
#
#  config.vm.define "web" do |web|
#    web.vm.box = "apache"
#  end
#
#  config.vm.define "db" do |db|
#    db.vm.box = "mysql"
#  end
#end
