# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  number_of_machines = 2
  box_name = "generic/ubuntu2004"
  
  base_ip = 100
  base_ip_addresses = "192.168.53"
  
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "host#{i}" do |box|
      box.vm.box = box_name
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"
  
      box.vm.hostname = "host#{i}"

    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end



# make sure /etc/hosts have correct entries
# Run the following rabbitmqctl commands on host2 server to add them to the RabbitMQ cluster (host1).

# Stop RabbitMQ application
# sudo rabbitmqctl stop_app

# Join the RabbitMQ node01
#sudo rabbitmqctl join_cluster rabbit@host1
#
# Start the RabbitMQ application again
#sudo rabbitmqctl start_app
#
#sudo rabbitmqctl cluster_status
