# -*- mode: ruby -*-
# vi: set ft=ruby :
#export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|
  number_of_machines = 2
  box_name = "generic/ubuntu2004"
  
  base_ip = 100
  base_ip_addresses = "192.168.55"
  
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  
  script = <<-SCRIPT
    echo "hello world"
    apt update
  SCRIPT
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "node0#{i}" do |box|
      box.vm.box = box_name
      
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"
  
      box.vm.hostname = "node0#{i}"
      box.vm.provision "shell", inline: "#{script}"


      if "node0#{i}"  == "node01" then
          box.vm.disk :disk, name: "lxc_1", size: "2GB"
          box.vm.disk :disk, name: "lxc_2", size: "2GB"
      end
      if "node0#{i}"  == "node02" then
          box.vm.disk :disk, name: "lxc_3", size: "2GB"
          box.vm.disk :disk, name: "lxc_4", size: "2GB"
      end
    end
  end
end
