Vagrant.configure("2") do |config|
  config.vm.define "cpu1" do |lab1b|
    lab1b.vm.box = "generic/ubuntu2004"
    lab1b.vm.hostname = "cpu1"
    lab1b.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    lab1b.vm.disk :disk, name: "sdb", size: "10GB"
  end
end


