Vagrant.configure("2") do |config|
  config.vm.define "cpu1" do |lab1b|
    lab1b.vm.box = "ubuntu/focal64"
    lab1b.vm.hostname = "cpu1"
    lab1b.vm.disk :disk, size: "40GB", primary: true
    lab1b.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
