---
- hosts: server1
  become: yes
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: ensure nginx is at the latest version
    apt:
      pkg:
      - vim
      - apt-transport-https
      - wget
      - curl
      - software-properties-common
      update_cache: yes
      state: latest

  #  Настройте ваш удаленный виртуальный сервер на принятие логов на TCP порте 5514 и записи только логов из facility local2 в файл /var/log/remote.

  - name: rsyslog on 5514 port TCP
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^#module\(load="imtcp"\)'
      line: 'module(load="imtcp")'

  - name: rsyslog on 5514 port TCP 2
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^#input\(type="imtcp" port="514"\)'
      line: 'input(type="imtcp" port="5514")'

  - name: Make sure a service is running
    systemd:
      state: restarted
      name: rsyslog

  - name: output localy executed task
    debug:
      msg: 'Настройте вашу локальную виртуальную машину на отправку всех логов facility local2 на ваш удаленный виртуальный сервер и в файл /var/log/local2.'
  
  - name: output localy executed task 1
    debug:
      msg: 'local2.*                        @@165.22.18.178:5514'

  - name: output localy executed task 2
    debug:
      msg: 'local2.*                        /var/log/local2'
  
  - name: send logs to  /var/log/remote
    lineinfile:
      path: /etc/rsyslog.conf
      line: 'local2.*                        /var/log/remote'

  - name: use logger locally
    debug:
      msg: "echo 'Rsyslog test' | logger --priority local2.emerg"



