---

- hosts: server1
  become: true
  vars:
    - mysql_root_password: "Password1"
  tasks:
  - name: Удалить пакеты mariadb-server=1:10.3.22-1ubuntu1 и т.д.
    apt:
      pkg: 
      - postgresql-12=12.2-4
      state: present
      update_cache: yes

  - name: create DB rebrain
    become: true
    become_user: postgres
    command: psql -c 'CREATE DATABASE rebrain;'
    ignore_errors: yes

  - name: create user 'student' with password 'pass'
    become: true
    become_user: postgres
    command: psql -c "create user student with encrypted password 'pass';"
    ignore_errors: yes

  - name: add all privileges to a new database
    become: true
    become_user: postgres
    command: psql -c "grant all privileges on database rebrain to student;"
    ignore_errors: yes

  - name: "Print link for sequence creation"
    debug:
      msg: https://www.postgresqltutorial.com/postgresql-sequences/

####create user student with encrypted password 'pass';
####grant all privileges on database rebrain to student;



####  - name: Установите пакет mariadb-server=1:10.3.22-1ubuntu1
####    apt:
####      pkg: 
####      - mariadb-server=1:10.3.22-1ubuntu1
####      - mariadb-common=1:10.3.22-1ubuntu1
####      - mariadb-client=1:10.3.22-1ubuntu1
####      - mariadb-server-10.3=1:10.3.22-1ubuntu1
####      - mariadb-client-10.3=1:10.3.22-1ubuntu1
####      - mariadb-server-core-10.3=1:10.3.22-1ubuntu1
####      - mariadb-client-core-10.3=1:10.3.22-1ubuntu1
####      - python3-mysqldb
####      force: yes
####      state: present
####      update_cache: yes
####
####  - name: start mariadb
####    service:
####      name: mariadb
####      enabled: true
####      state: started
####
####  - name: Check if mysql root password was not set
####    shell: >
####      mysql -u root
####      -h localhost
####      -e "quit"
####    changed_when: false
####    ignore_errors: true
####    register: check_passwd_root
####  
####  - name: Check if unix_socket plugin is enabled
####    shell: >
####      mysql -u root
####      -h localhost
####      -e "SELECT plugin from mysql.user WHERE user = 'root'"
####    ignore_errors: true
####    register: check_unix_socket_plugin
####    changed_when: check_unix_socket_plugin.stdout is search('socket')
####    when: check_passwd_root.rc == 0
####
####  - name: Delete remote login connection
####    shell: >
####      mysql -u root
####      -h localhost
####      -e "delete from mysql.user where User='root' and Host NOT IN ('localhost', '127.0.0.1');"
####    when:
####      - allow_remote_connections
####      - check_passwd_root.rc == 0
####
####  - name: Set MariaDB root password for 127.0.0.1, localhost
####    mysql_user:
####      name: root
####      password: "{{ mysql_root_password }}"
####      host: "{{ item }}"
####      login_user: root
####      #login_password: "{{ mysql_root_password }}"
####      login_unix_socket: "{{ mariadb_socket }}"
####      state: present
####    with_items:
####      - 127.0.0.1
####      - localhost
####    when: check_passwd_root.rc == 0
####
####  - name: Flush Priviliges
####    command: mysql -u root -p{{ mysql_root_password }} -e "FLUSH PRIVILEGES" 
####  - name: Remove all anonymous user
####    mysql_user:
####      login_user: root
####      login_password: "{{ mysql_root_password }}"
####      name: 'ansible'
####      host_all: yes
####      state: absent
####    notify: Flush Priviliges
####  
####  - name: Remove test database
####    mysql_db:
####      login_user: "root"
####      login_password: "{{ mysql_root_password }}"
####      db: "test"
####      state: absent
####    register: remove_test_db
####    
####
####  - name: start mariadb
####    service:
####      name: mariadb
####      enabled: true
####      state: started
####
####
####  - name: Create file for slow logs
####    file:
####      path: /var/log/mysql/mysql-slow.log
####      owner: mysql
####      group: mysql
####      mode: '0644'
####      state: touch
####
####
####  - name: Убедитесь в том, что включена настройка InnoDB File-per-table + skip-name-resolve + tmp_table_size. Приведите строку конфигурации в ответе.
####    replace:
####      path: /etc/mysql/mariadb.conf.d/50-server.cnf
####      regexp: '\[mysqld\]\n\n'
####      replace: |-
####        [mysqld]
####        innodb_file_per_table=on
####        skip-name-resolve=on
####        tmp_table_size=134217728
####        slow_query_log = 1
####        slow_query_log_file = /var/log/mysql/mysql-slow.log
####        long_query_time = 1
####        interactive_timeout = 60
####        wait_timeout = 60
####        max_connections = 200
####        query_cache_size = 256M
####
####  - name: restart mariadb
####    service:
####      name: mariadb
####      enabled: true
####      state: restarted
####
####  - name: sysbench install repo
####    shell: >
####      curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | sudo bash
####    changed_when: false
####    ignore_errors: true
####
####  - name: Install sysbench package
####    apt:
####      pkg: 
####      - sysbench
####      state: present
####      update_cache: yes
####
####  - name: Clone sysbench tests
####    git:
####      repo: 'https://github.com/akopytov/sysbench.git'
####      dest: /tmp
####
####  - name: Clone sysbench tests
####    git:
####      repo: 'https://github.com/akopytov/sysbench.git'
####      dest: /tmp
####
####  - name: "Print commands to run on the host to prepare for test"
####    debug:
####      msg: sysbench /tmp/sysbench/src/lua/oltp_common.lua --table-size=1000000 --db-driver=mysql --mysql-db=test --mysql-user=root --mysql-password=Password1 prepare
####
####  - name: "Print commands to run on the host to test"
####    debug:
#####      msg: sysbench /tmp/sysbench/src/lua/oltp_common.lua --table-size=1000000 --db-driver=mysql --mysql-db=test --mysql-user=root --mysql-password=Password1 --max-time=60 --oltp-read-only=on --max-requests=200 --num-threads=8 run
#####      msg: sysbench ./src/lua/oltp_common.lua --table-size=1000000 --db-driver=mysql --mysql-db=test --mysql-user=root --mysql-password=Password1 --time=60 --events=200 --threads=8 run
####      msg: root@first-task-1:~/sysbench# sysbench ./src/lua/oltp_read_write.lua --table-size=1000000 --db-driver=mysql --mysql-db=test --mysql-user=root --mysql-password=Password1 --time=120 --events=10000 --threads=200 run
####
####
####
