# -*- mode: ruby -*-
# vi: set ft=ruby :
#export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|
  number_of_machines = 2
  box_name = "generic/ubuntu1804"
  
  base_ip = 100
  base_ip_addresses = "192.168.56"
  
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  
  script = <<-SCRIPT
    echo "hello world"
  SCRIPT
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "squid#{i}" do |box|
      box.vm.box = box_name
      
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"
  
      box.vm.hostname = "squid#{i}"
      box.vm.provision "shell", inline: "#{script}"


      #if "iscsi#{i}"  == "iscsi1" then
			#  box.vm.disk :disk, name: "lxc_1", size: "2GB"
      #end
    end
  end
end
