---
#    Установите пакет php-fpm (сохраните команду для установки).
#    Напишите конфигурационный файл для PHP-FPM pool, который устанавливает следующие параметры:
#
#    имя pool - rebrainme;
#    пользователь и группа, от имени которых запущен pool, - www-data;
#    pool должен слушать на Unix-сокете;
#    использовал фиксированно 10 процессов для обработки запросов.
#
#    Напишите конфигурационный файл для nginx, который реализует следующую функциональность:
#
#    слушает на порте 8081;
#    проксирует все запросы на описанный PHP-FPM pool;
#    в роли index использовать файл с phpinfo из https://www.php.net/manual/ru/function.phpinfo.php из директории /var/www/phpinfo.
#

- hosts: server1
  become: true
  tasks:
  - name: Установите пакет nginx-full,apache2-utils,python3-pip.
    apt:
      pkg: 
      - nginx-full
      - php7.4-fpm
      - vim-nox
      update_cache: yes

  - name: Create directory /var/www/phpinfo
    file:
      dest: /var/www/phpinfo
      owner: www-data
      group: www-data
      state: directory

  - name: Download php file
    get_url:
      url: http://rebrainme.com/files/logo_rebrain_black.png
      dest: /var/www/rebrain/images/logo.png 
      mode: '0644'

####  - name: Install passlib python package
####    pip:
####      name: passlib
####
####  - name: Отключен модуль mail.
####    file:
####      path: /etc/nginx/modules-enabled/50-mod-mail.conf
####      state: absent
####
####  - name: Create directory /var/www/rebrain/images/
####    file:
####      dest: /var/www/rebrain/images
####      owner: root
####      group: root
####      state: directory
####
####  - name: Download rebrain logo
####    get_url:
####      url: http://rebrainme.com/files/logo_rebrain_black.png
####      dest: /var/www/rebrain/images/logo.png 
####      mode: '0644'
####
####  - name: Put a new nginx file
####    get_url:
####      url: http://rebrainme.com/files/logo_rebrain_black.png
####      dest: /var/www/rebrain/images/logo.png 
####      mode: '0644'
####
####  - name: Template a file to /etc/nginx/sites-enabled/default
####    vars:
####      domain: '157.230.30.66.nip.io'
####    ansible.builtin.template:
####      src: ./default.j2
####      dest: /etc/nginx/sites-enabled/default
####      owner: root
####      group: root
####      mode: '0644'
####
####  - name: Add a user to a password file and ensure permissions are set
####    htpasswd:
####      path: /etc/nginx/passwdfile
####      name: rebrain
####      password: 'linux'
####      owner: root
####      group: www-data
####      mode: 0640
#### 
####  - name: Restart nginx
####    service: name=nginx state=restarted 
####
####  - name: check_mode example
####    command:
####      cmd: cat /etc/nginx/sites-enabled/default
####    register: nginx_conf
####
####  - name: Output /etc/nginx/sites-enabled/default
####    debug:
####      msg: Nginx.conf file has content {{ nginx_conf }}
####  
