Vagrant.configure("2") do |config|
  config.vm.define "cpu1" do |lab1b|
    lab1b.vm.box = "generic/ubuntu2004"
    lab1b.vm.hostname = "cpu1"
    lab1b.vm.provider "virtualbox" do |vb|
    lab1b.vm.network "private_network", ip: "172.16.16.100"
      vb.memory = 1024
      vb.cpus = 2
    end
  end
end


