Vagrant.configure("2")do|config|
  config.vm.box="hashicorp/precise64"
  config.vm.synced_folder"./","/vagrant"
  config.vm.define"web" do |web|
    web.vm.network:private_network, ip:"192.168.33.101"
    web.vm.provision"ansible"do|ansible|
      ansible.playbook="ansible/playbook_webserver.yml"
    end
    web.vm.synced_folder"./myapp/","/vagrant",:nfs=>true
  end
  config.vm.define"db"do|db|
    db.vm.network:private_network, ip:"192.168.33.102"
    db.vm.provision"ansible"do|ansible|
      ansible.playbook="ansible/playbook_dbserver.yml"
    end
  end
end
