Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu2004"

    config.vm.network :private_network, ip: "192.168.33.101", virtualbox__intnet: true


    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end

#    config.vm.synced_folder "../../testapp", "/vagrant", :nfs => true

end
