---

- hosts: server1
  become: true
  vars:
    - mysql_root_password: "Password1"
  tasks:
  - name: Install redis-server
    apt:
      pkg: 
      - redis-server
      state: present
      update_cache: yes


  - name: Сконфигурируйте Redis на RDB метод бэкапа, с тем, чтобы он сохранял дамп 
    replace:
      path: /etc/redis/redis.conf
      regexp: 'save 900 1\nsave 300 10\nsave 60 10000\n'
      replace: |-
        save 3600 1
        save 1800 10
        save 300 10000

  - name: максимально разрешенное количество клиентов до 10000
    replace: 
      path: /etc/redis/redis.conf
      regexp: '# maxclients 10000'
      replace: |-
        maxclients 10000

  - name: policy to 'volatile-lru'
    replace:
      path: /etc/redis/redis.conf
      regexp: '# maxmemory-policy noeviction'
      replace: |-
        maxmemory-policy volatile-lru

  - name: restart redis-server
    service:
      name: redis-server
      state=restarted
      enabled=yes

  - name: Воспользуйтесь утилитой redis-benchmark и протестируйте вашу инсталляцию, имитируя 100 параллельных соединений (имитация количества клиентов). Протестировав 200000 запросов, данные выведите в quiet-формате. Также протестируйте задержку с помощью redis-cli. Команды и вывод приведите в качестве ответа.
    debug:
      msg: redis-benchmark -h localhost -c 100 -n 200000 -q


  - name: Также протестируйте задержку с помощью redis-cli. Команды и вывод приведите в качестве ответа.
    debug:
      msg: redis-cli --latency -h 127.0.0.1 -p 6379

