version: '3.1'

services:

  db:
    image: mariadb:10.8-rc-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    network_mode: host
    volumes:
      - ./init:/docker-entrypoint-initdb.d
