# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder"./","/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install apt-transport-https ca-certificates dirmngr -y
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4
    
    echo "deb https://repo.clickhouse.com/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list
    sudo apt-get update
    
    DEBIAN_FRONTEND=noninteractive apt-get install -y clickhouse-server clickhouse-client
    sudo service clickhouse-server start

    cat << EOF > /etc/clickhouse-server/config.d/main.xml
    <?xml version="1.0"?>
    <clickhouse>
        <http_port>8125</http_port>
        <max_concurrent_queries>100</max_concurrent_queries>
        <timezone>UTC</timezone>
    </clickhouse>
    EOF

    systemctl restart clickhouse-server
    systemctl status clickhouse-server
    
    curl http://localhost:8125
    
  SHELL
end
