# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  number_of_machines = 2
  box_name = "generic/ubuntu2004"
  
  base_ip = 9
  base_ip_addresses = "192.168.10"
  
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  
####  script = <<-SCRIPT
####    echo "hello world"
####    apt update
####    apt install vim keepalived -y
####
####  SCRIPT
####  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "LB#{i}" do |box|
      box.vm.box = box_name
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}",virtualbox__intnet: "keepalived__net"
      box.vm.hostname = "LB#{i}"
      config.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbook.yml"
      end

    end
  end

end
