---
- hosts: server1
  become: yes
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: ensure nginx is at the latest version
    apt:
      pkg:
      - vim
      - apt-transport-https
      - wget
      - software-properties-common
      state: latest
  - name: gpg key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: Add specified repository into sources list using specified filename
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present
      filename: grafana.list
  - name: install grafana
    apt:
      pkg:
      - grafana
      update_cache: yes

  - name: Restart service grafana in all cases, also issue daemon-reload to pick up config changes
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: 'grafana-server.service'
  
  - name: create prometheus datasource
    grafana_datasource:
      name: prometheus
      ds_type: prometheus
      ds_url: "http://{{ ansible_host }}:9090"
      grafana_url: "http://{{ ansible_host }}:3000"
      access: direct
      tls_skip_verify: true
  
  - name: Create a Grafana user
    community.grafana.grafana_user:
      url: "http://{{ ansible_host }}:3000"
      url_username: admin
      url_password: admin
      name: "admin"
      email: admin@google.com
      login: admin
      password: rebrainme
      is_admin: true
      state: present
#  
#
#sudo apt-get install -y software-properties-common wget
#wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
#echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
#sudo apt-get update
#sudo apt-get install grafana
#sudo systemctl daemon-reload
#sudo systemctl start grafana-server
#sudo systemctl status grafana-server


