# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  number_of_machines = 2
  box_name = "generic/ubuntu1804"
  
  base_ip           = 100
  base_ip_addresses = "192.168.33"
  net_with_server   = "192.168.111"
  
  ip_addresses             = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  ip_addresses_with_server = (1..number_of_machines).map{ |i| "#{net_with_server}.#{base_ip + i}" }
  
  script = <<-SCRIPT
    echo "hello world"
    apt update
    apt install openvpn bridge-utils -y 
    echo '192.168.33.101 openvpnserver.example.com' >> /etc/hosts
    echo '192.168.33.102 openvpnclient.example.com' >> /etc/hosts
    echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf
    sysctl -p
  SCRIPT
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "vpn#{i}" do |box|
      box.vm.box = box_name
      box.vm.hostname = "vpn#{i}"
      
      if box.vm.hostname  == "vpn1" then
        box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"
        box.vm.network "private_network", ip: "192.168.111.101", name: "server_net1"
      elsif box.vm.hostname  == "vpn2" then
        box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"
        box.vm.network "private_network", ip: "192.168.111.102", name: "server_net2"
      end 

      box.vm.provision "shell", inline: "#{script}"

    end
  end

  config.vm.define "separatehost3" do |box|
    box.vm.box = box_name
    box.vm.network "private_network", ip: "192.168.111.103", name: "server_net1"
    box.vm.hostname = "separatehosts3"
    box.vm.provision "shell", inline: "#{script}"
  end


  config.vm.define "separatehost4" do |box|
    box.vm.box = box_name
    box.vm.network "private_network", ip: "192.168.111.104", name: "server_net2"
    box.vm.hostname = "separatehosts4"
    box.vm.provision "shell", inline: "#{script}"
  end




end

#####On client side
####openvpn --mktun --dev tap0
####brctl addbr br0
####brctl addif br0 eth2
####brctl addif br0 tap0
####ifconfig eth2 0.0.0.0 up
####ifconfig tap0 0.0.0.0 up
####ifconfig br0 192.168.111.222 netmask 255.255.255.0 up
####
#####On server side
####openvpn --mktun --dev tap0
####brctl addbr br0
####brctl addif br0 eth2
####brctl addif br0 tap0
####ifconfig eth2 0.0.0.0 up
####ifconfig tap0 0.0.0.0 up
####ifconfig br0 192.168.111.111 netmask 255.255.255.0 up






