Vagrant.configure("2") do |config|
  config.vm.define "cpu1" do |lab1b|
    lab1b.vm.box = "generic/ubuntu2004"
    lab1b.vm.hostname = "cpu1"
    lab1b.vm.provider "virtualbox" do |vb|
      vb.memory = 3072
    end
    lab1b.vm.provision "file", source: "./1_cpu_load_enable.sh", destination:  "~/1_cpu_load_enable.sh"
    lab1b.vm.provision "file", source: "./1_cpu_load_disable.sh", destination: "~/1_cpu_load_disable.sh"
  end
end


