# -*- mode: ruby -*-
# vi: set ft=ruby :
#export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|
  number_of_machines = 2
  box_name = "generic/ubuntu2004"
  
  base_ip = 3
  base_ip_addresses = "192.168.10"
  
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  
  script = <<-SCRIPT
    apt update
  SCRIPT
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "nfs#{i}" do |box|
      box.vm.box = box_name
      
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"
#      box.vm.network "private_network", ip: "10.10.10.1", auto_config: false
  
      box.vm.hostname = "nfs#{i}"
#      box.vm.provision "ansible" do |ansible|
#          ansible.playbook = "playbook.yml"
#          #ansible.verbose='vvv'#accepted values:from'v'to'vvvv'
#      end

    end
  end
end
